<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-12-06 12:57
=======
# Generated by Django 2.0.5 on 2018-12-08 01:26
>>>>>>> 94edc6d85d5e3e18705ca09c3f9b87ecc786de7c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('about', models.TextField()),
                ('usage', models.TextField()),
                ('manufacturedBy', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
