# Generated by Django 2.1.2 on 2018-11-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='title',
            new_name='name',
        ),
    ]
