# Generated by Django 2.0.5 on 2018-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
