# Generated by Django 2.1.2 on 2018-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0002_auto_20181101_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='medicine_img'),
        ),
    ]
