# Generated by Django 2.1.2 on 2018-11-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0003_medicine_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
    ]
