# Generated by Django 2.1.2 on 2018-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0004_remove_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/img/ShopOnline/'),
        ),
    ]
