# Generated by Django 2.1.2 on 2018-11-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0005_medicine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/ShopOnline/'),
        ),
    ]
