# Generated by Django 2.1.2 on 2018-11-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0008_auto_20181112_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='image',
        ),
    ]
