# Generated by Django 2.1.2 on 2018-11-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0011_auto_20181112_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.FloatField(),
        ),
    ]
