# Generated by Django 2.1.2 on 2018-11-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingPortalApp', '0013_auto_20181112_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='manufacturedBy',
            field=models.TextField(),
        ),
    ]
