# Generated by Django 2.0.5 on 2018-12-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=40)),
                ('bank_id', models.CharField(max_length=10)),
                ('card_no', models.IntegerField()),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Rupay', 'Rupay'), ('Master Card', 'Master Card')], max_length=20)),
                ('card_cvv', models.IntegerField()),
                ('bank_balance', models.FloatField(default=3000)),
            ],
        ),
    ]
