# Generated by Django 2.0.5 on 2018-12-11 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='Bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bank'),
        ),
    ]
