# Generated by Django 2.0.5 on 2018-12-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20181211_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='card_no',
            field=models.CharField(max_length=20),
        ),
    ]
