# Generated by Django 2.0.5 on 2018-12-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20181211_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('card_no', models.CharField(max_length=20)),
                ('card_type', models.CharField(choices=[('Visa', 'Visa'), ('Rupay', 'Rupay'), ('Master Card', 'Master Card')], max_length=20)),
                ('card_cvv', models.IntegerField()),
                ('bank_balance', models.FloatField(default=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='bank_balance',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='onlinepayment',
            name='Bank',
        ),
        migrations.AddField(
            model_name='bank_customer',
            name='Bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bank'),
        ),
        migrations.AddField(
            model_name='onlinepayment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bank_customer'),
        ),
    ]
