# Generated by Django 2.0.5 on 2018-12-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20181211_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinepayment',
            name='amount_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
