# Generated by Django 2.1.2 on 2018-11-16 22:01

import booking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.CharField(max_length=20)),
                ('doctor_id', models.CharField(max_length=250)),
                ('rmp_id', models.CharField(max_length=250)),
                ('transaction_id', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PaitentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('mobile_no', models.BigIntegerField()),
                ('symptoms', models.CharField(max_length=250)),
                ('description_of_illness', models.CharField(max_length=250)),
                ('checkout_id', models.CharField(default=booking.models.generateUUID, editable=False, max_length=36, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointmentdetials',
            name='paitent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.PaitentDetails'),
        ),
    ]
