# Generated by Django 2.0.5 on 2018-12-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paitentdetails',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
