# Generated by Django 2.0.5 on 2018-11-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetials',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdetials',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
