# Generated by Django 2.1.2 on 2018-11-17 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetials',
            name='paitent_id',
        ),
        migrations.AddField(
            model_name='appointmentdetials',
            name='checkout_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.PaitentDetails'),
        ),
        migrations.AlterField(
            model_name='paitentdetails',
            name='doctor_id',
            field=models.CharField(blank=True, editable=False, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paitentdetails',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
