# Generated by Django 2.0.5 on 2018-11-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181126_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetials',
            name='date',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_profile.BookingDate'),
        ),
    ]
