# Generated by Django 2.0.5 on 2018-12-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_paitentdetails_is_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paitentdetails',
            name='is_attended',
        ),
        migrations.AddField(
            model_name='appointmentdetials',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
