# Generated by Django 2.1.2 on 2018-12-06 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181202_1632'),
        ('booking', '0003_appointmentdetials_user'),
    ]

    operations = [
    ]
