# Generated by Django 2.1.2 on 2018-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prescription_Item',
            new_name='Item',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
