# Generated by Django 2.1.2 on 2018-11-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_medicine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
