# Generated by Django 2.1.2 on 2018-11-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_auto_20181103_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='medicine_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_name',
            new_name='name',
        ),
    ]
