# Generated by Django 2.1.2 on 2018-11-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_auto_20181103_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
