# Generated by Django 2.1.2 on 2018-11-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_auto_20181103_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='medicine_name',
            new_name='name',
        ),
    ]
