# Generated by Django 2.1.2 on 2018-11-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_auto_20181103_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
