<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-12-12 16:35
=======
# Generated by Django 2.0.5 on 2018-12-12 16:55
>>>>>>> d629ccf7d1882becd6bed614d73969e4b3e3b3b0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
            ],
        ),
    ]
