<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-12-06 12:56
=======
# Generated by Django 2.0.5 on 2018-12-08 01:25
>>>>>>> 94edc6d85d5e3e18705ca09c3f9b87ecc786de7c

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=20)),
                ('password1', models.CharField(max_length=20)),
            ],
        ),
    ]
