<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-12-06 12:57
=======
# Generated by Django 2.0.5 on 2018-12-08 01:26
>>>>>>> 94edc6d85d5e3e18705ca09c3f9b87ecc786de7c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('rmp', '0001_initial'),
        ('shoppingPortalApp', '__first__'),
=======
        ('shoppingPortalApp', '__first__'),
        ('rmp', '0001_initial'),
>>>>>>> 94edc6d85d5e3e18705ca09c3f9b87ecc786de7c
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shoppingPortalApp.medicine')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shopping_cart.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmp.rmpContact'),
        ),
    ]
