<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-12-07 12:20
=======
# Generated by Django 2.0.5 on 2018-12-04 12:00
>>>>>>> 4bfaaa03ba4c18689d6a17676e9e405ea7c5a376

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rmp', '0001_initial'),
<<<<<<< HEAD
        ('shoppingPortalApp', '__first__'),
=======
        ('shoppingPortalApp', '0001_initial'),
>>>>>>> 4bfaaa03ba4c18689d6a17676e9e405ea7c5a376
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=15)),
                ('patient_name', models.CharField(default=None, max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
=======
                ('deliver_addr_houseno', models.CharField(default=None, max_length=30)),
                ('deliver_addr_street', models.CharField(default=None, max_length=30)),
                ('deliver_addr_area', models.CharField(default=None, max_length=30)),
                ('deliver_addr_district', models.CharField(default=None, max_length=20)),
                ('deliver_addr_state', models.CharField(default=None, max_length=15)),
                ('deliver_addr_country', models.CharField(default=None, max_length=15)),
>>>>>>> 4bfaaa03ba4c18689d6a17676e9e405ea7c5a376
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shoppingPortalApp.medicine')),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='shopping_cart.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmp.rmpContact'),
        ),
    ]
