# Generated by Django 2.0.5 on 2018-12-04 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='patient_name',
        ),
    ]
