# Generated by Django 2.0.5 on 2018-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_remove_order_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliver_addr_area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_addr_country',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_addr_district',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_addr_houseno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_addr_state',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_addr_street',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
