# Generated by Django 2.0.5 on 2018-11-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0002_rmpcontact_medicines'),
        ('shopping_cart', '0002_order_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code_order', models.CharField(max_length=15)),
                ('is_ordered', models.BooleanField(default=False)),
                ('Items', models.ManyToManyField(to='shopping_cart.OrderItem')),
                ('Owner', models.ManyToManyField(to='rmp.rmpContact')),
            ],
        ),
    ]
