# Generated by Django 2.0.5 on 2018-12-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_auto_20181204_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_addr_area',
        ),
        migrations.AddField(
            model_name='order',
            name='deliver_addr_pincode',
            field=models.IntegerField(null=True),
        ),
    ]
