# Generated by Django 2.0.5 on 2018-12-07 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20181207_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patient_name',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='patient_phno',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
