# Generated by Django 2.0.5 on 2018-12-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_auto_20181207_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
