# Generated by Django 2.0.5 on 2018-12-07 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0008_auto_20181207_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient_phno',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000)]),
        ),
    ]
