# Generated by Django 2.0.5 on 2018-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_auto_20181207_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='patient_phno',
            field=models.IntegerField(),
        ),
    ]
