# Generated by Django 2.0.5 on 2018-12-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0012_auto_20181207_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Pay Online', 'Pay Online')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
