# Generated by Django 2.1.2 on 2018-11-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('charges', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
            ],
        ),
    ]
