# Generated by Django 2.1.2 on 2018-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='doctor/'),
        ),
    ]
