# Generated by Django 2.1.2 on 2018-11-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_auto_20181103_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='charges',
            new_name='price',
        ),
    ]
