# Generated by Django 2.1.2 on 2018-11-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_auto_20181107_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='username',
            new_name='products',
        ),
    ]
