# Generated by Django 2.1.2 on 2018-11-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_auto_20181107_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='products',
            new_name='username',
        ),
    ]
