# Generated by Django 2.1.2 on 2018-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_auto_20181107_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=40.5, max_digits=10),
        ),
    ]
