# Generated by Django 2.0.5 on 2018-12-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_profile.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('doctor', 'start_time', 'date')},
        ),
    ]
