# Generated by Django 2.0.5 on 2018-12-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_id',
        ),
    ]
