# Generated by Django 2.0.5 on 2018-11-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor_id',
        ),
    ]
