# Generated by Django 2.0.5 on 2018-11-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0002_auto_20181124_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.CharField(choices=[('ORTHOPAEDIC', 'ORTHOPAEDIC'), ('GYNACEOLOGIST', 'GYNACEOLOGIST'), ('ONCOLOGIST', 'ONCOLOGIST'), ('NEUROLOGIST', 'NEUROLOGIST')], editable=False, max_length=250),
        ),
    ]
