# Generated by Django 2.1.2 on 2018-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0002_auto_20181028_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(default='skg', max_length=20, unique=True),
        ),
    ]
