# Generated by Django 2.0.5 on 2018-11-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0003_auto_20181124_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.CharField(max_length=250),
        ),
    ]
