# Generated by Django 2.1.2 on 2018-10-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0004_auto_20181028_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor_id',
            field=models.CharField(default='skg', max_length=20, unique=True),
        ),
    ]
