# Generated by Django 2.0.5 on 2018-11-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0004_auto_20181124_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_id',
            field=models.CharField(editable=False, max_length=250),
        ),
    ]
