# Generated by Django 2.0.5 on 2018-11-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0008_bookingdate_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
