# Generated by Django 2.0.5 on 2018-11-24 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0009_auto_20181124_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdate',
            name='date',
            field=models.DateField(default=datetime.datetime.now, unique=True),
        ),
    ]
