# Generated by Django 2.1.2 on 2018-11-17 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0011_auto_20181117_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
