# Generated by Django 2.0.5 on 2018-11-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0015_auto_20181127_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.CharField(blank=True, choices=[('09:00:00', '6 am'), ('12:00:00', '12 pm'), ('04:00:00', '4 pm')], max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('start_time', 'date')},
        ),
    ]
