# Generated by Django 2.1.2 on 2018-11-09 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rmpContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('age', models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default='male', max_length=10)),
                ('qualifications', models.CharField(max_length=30)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=6)),
                ('phone_no', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='rmpLogData',
            fields=[
                ('userlogId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rmpPatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paitent_id', models.CharField(max_length=10, null=True, unique=True)),
                ('paitent_fullname', models.CharField(max_length=120)),
                ('paitent_age', models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('paitent_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('others', 'OTHERS')], default='male', max_length=10)),
                ('paitent_locality', models.CharField(max_length=100)),
                ('paitent_city', models.CharField(max_length=100)),
                ('paitent_district', models.CharField(max_length=100)),
                ('paitent_country', models.CharField(max_length=100)),
                ('paitent_type_of_ailment', models.CharField(max_length=120)),
                ('description_of_ailment', models.CharField(max_length=120)),
                ('paitent_phone_no', models.CharField(max_length=11)),
                ('rmp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rmp.rmpLogData')),
            ],
        ),
        migrations.AddField(
            model_name='rmpcontactdetail',
            name='userlogId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rmp.rmpLogData'),
        ),
    ]
