# Generated by Django 2.0.5 on 2018-12-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmpcontact',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
